# -*- coding: utf-8 -*-

import unittest
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()
    # tests = [unittest.TestLoader().loadTestsFromName('test_mathfunc.TestMathFunc')]
    tests = [unittest.TestLoader().loadTestsFromNames(['test_mathfunc.TestMathFunc.test_multi','test_mathfunc.TestMathFunc.test_minus'\
, 'test_mathfunc.TestMathFunc.test_add','test_mathfunc.TestMathFunc.test_divide'])]
    # tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_multi"), TestMathFunc("test_divide")]
    suite.addTests(tests)

    with open('HTMLReport.html', 'wb+') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)