# -*- coding:utf-8 -*-

# A simple example using the HTTP plugin that shows the retrieval of a
# single page via HTTP.
#
# This script is automatically generated by ngrinder.
#
# @author admin
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from HTTPClient import Cookie, CookieModule, CookiePolicyHandler, NVPair
from org.json import JSONObject
import PTS #自定义的库，后续大家可扩充。

control = HTTPPluginControl.getConnectionDefaults()
# if you don't want that HTTPRequest follows the redirection, please modify the following option 0.
# control.followRedirects = 1
# if you want to increase the timeout, please modify the following option.
control.timeout = 600000 #超时时间10分钟

def tenant():
    statusCode = [0L, 0L, 0L, 0L]
    headers = [NVPair('Content-Type', 'application/json'),NVPair('Accept', 'application/json'),NVPair('Origin', '10.1.11.254')]
    data = '{"message":{"toUserList":[],"content":"同意"},"executor":{},"modelId":"a7ea82fdd36b4348b5e242af1531bfd3","form":{"title":"性能测试工单ffff","urgentLevel":"4","ticketDesc":"性能测试工单001","startTime":"2017-11-01T09:32:01.550Z","announcer":"性能测试工单001","inCategory":"0"},"ticketSource":"web"}'
    result7 = HTTPRequest().POST('http://10.1.11.254/itsm/api/v2/ticket/createTicket/a7ea82fdd36b4348b5e242af1531bfd3', data, headers)
    code = result7.getStatusCode()
    data = result7.getText()
    json = JSONObject(data)
    grinder.logger.info(json.getString("errCode"))
    status = json.getString("errCode")
    if status == 'null':
        code = 300
    if status != 'null':
        code = int(status)
    PTS.addHttpCode(code, statusCode)
    return statusCode


# Make any method call on request1 increase TPS
Test(1,'test').record(tenant)

class TestRunner:
    # initlialize a thread
    def __init__(self):
        grinder.statistics.delayReports=True
        headers = [NVPair('Content-Type', 'application/json'),NVPair('Accept', 'application/json'),]
        #data = '{"email": "admin@uyun.cn","passwd": "0e7517141fb53f21ee439b355b5a1d0a"}'
        login_msg=PTS.get_tenant()
        lenth=len(login_msg)
        i=0
        #grinder.logger.info(login_msg[i][0])
        #grinder.logger.info(login_msg[i][1])
        data= '{"email": "%s", "passwd": "%s", "code": "uyun", "authCode": "YQTxa8TT6tnQ23IOt23YSAqotUw9KgItxqq4gem+n+f4KB5cINEWr4nMMLeTPBaZobmLzsm1nz9wjVm31fFjrQ=="}' % (login_msg[i][0], login_msg[i][1])
        #grinder.logger.info(data)
        if i >= lenth-1:
            i=0
        i+=1
        result = HTTPRequest().POST('http://10.1.11.254/tenant/api/v1/user/login', data, headers)
        self.threadContext = HTTPPluginControl.getThreadHTTPClientContext()
        self.login_cookies = CookieModule.listAllCookies(self.threadContext)

    # test method
    def __call__(self):
        sumStatusCode = [0L,0L,0L,0L]
        for c in self.login_cookies:
           CookieModule.addCookie(c, self.threadContext)        
        PTS.sumHttpCode(tenant(),sumStatusCode)
        if sum(sumStatusCode[1:4]) > 0:
            grinder.statistics.forLastTest.success = 0
            grinder.logger.error(u'事务请求中http 返回状态大于300，请检查请求是否正确!')
        else:
            grinder.statistics.forLastTest.success = 1
